name: Project Build
run-name: "ğŸ“¦ Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - dev
      - main
    tags:
      v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEV_ENVIRONMENT: ${{ github.ref_name != 'main' }}

jobs:
  info:
    name: ğŸ–¥ï¸ Project Info
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.check.outputs.project_name }}
      project_version: ${{ steps.check.outputs.project_version }}
      project_full_name: ${{ steps.check.outputs.project_name }}-${{ steps.check.outputs.project_version }}

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: ğŸ“ˆ Get latest tag
        id: latest_tag
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0 origin/main)
          if [ -z "$tag" ]; then
            echo "âŒ Latest tag not found" && exit 1
          else
            echo "âœ”ï¸ Latest tag found: $tag"
            echo "tag=$tag" >> $GITHUB_OUTPUT
          fi

      - name: ğŸ” Check
        id: check
        shell: bash
        run: |

          PROJECT_NAME=${{ github.event.repository.name }}

          if ${{ env.DEV_ENVIRONMENT == 'true' }}; then
            PROJECT_VERSION="build_#${{ github.run_number }}"
          else
            PROJECT_VERSION="${{ steps.latest_tag.outputs.tag }}"
          fi

          echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "project_version=$PROJECT_VERSION" >> $GITHUB_OUTPUT

  build-project:
    name: ğŸ“¦ Build Project
    needs: [info]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: ğŸ” Check
        id: check
        shell: bash
        run: |
          OUTPUT_FORMAT=zip
          ARTIFACT_FILE_NAME=${{ needs.info.outputs.project_full_name }}.$OUTPUT_FORMAT

          echo "output_format=$OUTPUT_FORMAT" >> $GITHUB_OUTPUT
          echo "artifact_file_name=$ARTIFACT_FILE_NAME" >> $GITHUB_OUTPUT

      - name: ğŸ“¦ Make datapack distibutive
        run: |
          cd src/
          git archive --format=${{ steps.check.outputs.output_format }} --output ../${{ steps.check.outputs.artifact_file_name }} HEAD

      - name: ğŸ” Check if artifact exist
        id: check_artifact
        shell: bash
        run: |
          if [ ! -f ${{ steps.check.outputs.artifact_file_name }} ]; then
            echo '::error::No value found for artifact `${{ steps.check.outputs.artifact_file_name }}`.' && exit 1
          fi
          echo "âœ”ï¸ Artifact has been found"

      - name: ğŸš€ Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ needs.info.outputs.project_full_name }}
          path: ${{ steps.check.outputs.artifact_file_name }}
          if-no-files-found: error
